"""remove current trip from user

Revision ID: 5208c52581cb
Revises: 6317303315eb
Create Date: 2023-07-12 08:08:31.220897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5208c52581cb'
down_revision = '6317303315eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_current_trip_collection_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'current_trip_collection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_trip_collection_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_current_trip_collection_id_fkey', 'users', 'collections', ['current_trip_collection_id'], ['id'])
    # ### end Alembic commands ###
